package com.accio.Student_Library_Management_System.Services;

import com.accio.Student_Library_Management_System.Enums.CardStatus;
import com.accio.Student_Library_Management_System.Models.Card;
import com.accio.Student_Library_Management_System.Models.Student;
import com.accio.Student_Library_Management_System.Repositories.StudentRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
public class StudentService {

    @Autowired
    StudentRepository studentRepository;
    public String createStudent(Student student){

        //Student from postman is already the basic attributes set

        //card should be autogenerated when createStudent function is called
        Card card = new Card();
        card.setCardStatus(CardStatus.ACTIVATED);
        card.setStudentVariableName(student);


        // lets go to student
        student.setCard(card);

        //If there was unidirectional mapping : we had to save both of them

        //but we are super advance and are using bidirectional  : child will automatically be saved

        studentRepository.save(student);

        // by cascading effect child will automatically be saved

        return "Student and card added";
    }
}
